### ISSUE TITLE
Add Conda Support

### ISSUE THREAD

**Issue by matajoh** [microsoft/scenepic#16]
Add `conda` packaging as part of CI/CD.

**Comment by jnyfah** [comment]
Hi @matajoh, published the package on conda you can check it out [here](https://anaconda.org/conda-forge/scenepic) 
But as of now, it works on Linux and macOS, I am still working on making it compatible with Windows.

here is a link to the [feedstock](https://github.com/conda-forge/scenepic-feedstock)

**Comment by matajoh** [comment]
Will this stay up to date, or do we need to add updating this to our release process?

**Comment by jnyfah** [comment]
Done with it.
