### ISSUE TITLE
Support for rendering large point clouds

### ISSUE THREAD

**Issue by fwilliams** [microsoft/scenepic#19]
Hi, 

This seems like a great visualization tool for 3D problems! It would be nice to have some support for rendering large colored and lit point clouds. I tried adding spheres to a scene (one per point) but this slowed down very quickly for even a moderately large number of spheres (~10-50k). It would be nice to have support for rendering very large point clouds!

**Comment by matajoh** [comment]
We absolutely support this! We have some examples in the tutorial for point clouds:

C++ tutorial starting at: https://github.com/microsoft/scenepic/blob/f695a2916a0f135bdcbe46a56340da6548b9ef12/src/examples/tutorial.cpp#L108

Python tutorial near the top: https://github.com/microsoft/scenepic/blob/main/python_examples/tutorial.ipynb

The key thing is to use the [`enable_instancing`](https://microsoft.github.io/scenepic/python/graphics3d.html?highlight=enable_instancing#scenepic.Mesh.enable_instancing) function on the mesh. It should be able to support as much as your graphics card can handle. Please let me know if this resolves your issue.

**Comment by fwilliams** [comment]
Thanks! This does work for me. I somehow missed the tutorial. I couldn't find a link in the main documentation. It would be really great to have a more fleshed out tutorial in the main documentation, but I'm sure this will happen eventually. Thanks for the cool library!

**Comment by matajoh** [comment]
Great feedback! We'll work on making this more front and center in our documentation, as it is a very common use case. Thanks!
