### ISSUE TITLE
How to set the playback fps for visualization?

### ISSUE THREAD

**Issue by pableeto** [microsoft/scenepic#26]
Hi,
I wonder how can I set the render fps for the scene? I've tried to search in the API documentation but get no results.
Thanks!

**Comment by tjcashman** [comment]
Hi,

Did you find the `Scene.framerate` property? (Docs for [Python](https://microsoft.github.io/scenepic/python/api.html#scenepic.Scene.framerate), [C++](https://microsoft.github.io/scenepic/cpp/classscenepic_1_1_scene.html#a1137b71930ed2878d2ed7825ea93d8c0)). Let us know if that solves the issue for you.

**Comment by pableeto** [comment]
Oh thanks! I was finding with something like "fps". 
Closing the issue.
