### ISSUE TITLE
Is it able to update vertex color for key frame?

### ISSUE THREAD

**Issue by pableeto** [microsoft/scenepic#27]
Hi,
I am using scenepic for visualizing and debugging my project, it is super cool!
Currently, I would like to visualize some error maps onto a mesh sequence via heat maps.
However I found either update_mesh_without_normals() or update_mesh() has no interface for changing per-vertex color.
Are there other ways to update per-vertex color for keyframes? Thanks a lot!

**Comment by matajoh** [comment]
This isn't currently a feature, but I think it makes a lot of sense for precisely this kind of use case. I'll add it to the backlog.
