### ISSUE TITLE
Jupyter examples with Visual Studio Code

### ISSUE THREAD

**Issue by pableeto** [microsoft/scenepic#39]
Hi,
Thanks for releasing this great library!

I am using Jupyter Notebooks in Visual Studio Code. 
When I run the "getting_started.ipynb" in python_examples, the final line of code 
```
# display the scene in Jupyter
scene
```
does not show anything in the output cell in Visual Studio Code Notebook.
What is the expected behavior and/or best practices of using scenepic with Jupyter in VS Code? 
Thanks a lot!

**Comment by matajoh** [comment]
The desired behavior is that it displays in the same way as it would in Jupyter or JupyterLab. I've reproduced the behavior locally, and am investigating why this is happening. However, at the moment this does appear to be broken.

**Comment by matajoh** [comment]
Just so you know this issue is being tracked and investigated here: microsoft/vscode-jupyter#11366

**Comment by matajoh** [comment]
I believe this is fixed in the latest version of the jupyter extension + version 1.0.16.
