### ISSUE TITLE
Add support for Apple Silicon chip

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/scenepic#46]
Thanks for the package, however I'm unable to use this on Mac M1 as there are no wheels for for the Apple Silicon chip.
Please consider adding support for apple silicon chips.

**Comment by matajoh** [comment]
Yes, this is a known issue. I was waiting (in hope) for hosted Github actions VMs with Apple Silicon, but that remains elusive. I may just need to get some physical hardware and build the wheels manually. I'll post in once we have support.

**Comment by matajoh** [comment]
I've found a workaround in the meantime using a cloud-hosted Mac M1 Mini. I'll ensure there is support moving forward for Apple Silicon for all future releases from 1.0.13 onwards.
