### ISSUE TITLE
Python API docs missing some functions

### ISSUE THREAD

**Issue by timhutton** [microsoft/scenepic#49]
Example:

The [python docs for Image](https://microsoft.github.io/scenepic/python/media.html#image) says that the only member function is `load`.

However there are additional member functions [`load_from_buffer` and `from_numpy`](https://github.com/microsoft/scenepic/blob/main/src/scenepic/image.py).

Presumably the issue is that the docs are generated from the C++?

**Comment by matajoh** [comment]
They definitely used to be there. It is possible this is a result of moving to using the interface stub files. I'll look into it.

**Comment by matajoh** [comment]
This appears to be a known issue: https://github.com/sphinx-doc/sphinx/issues/7630

I will see if I can find a workaround.
