### ISSUE TITLE
Toggle layer visibility with a keyboard shortcut

### ISSUE THREAD

**Issue by bednarikjan** [microsoft/scenepic#53]
Having the ability to turn on/off the visibility of a given layer within a canvas is extremely useful. However, one has to click the checkbox with a mouse pointer, which gets a bit tedious especially when one wants to repeatedly toggle the visibility of a layer (e.g. to visually compare it to the layer below). It would be very convenient to have keyboard shortcuts support for this action, e.g. CMD/CTRL + <layer_id>.

**Comment by matajoh** [comment]
Great suggestion!

**Comment by bednarikjan** [comment]
Thank you for adding this feature, it's incredibly useful!

I noticed that if a page has multiple canvases, the shortcut toggles the given layer across all the canvases simultaneously. Would it be possible to modify the behaviour so that the visibility is toggled only within a single "in focus" canvas?
